### ISSUE TITLE
Refactor: ToDo 삭제 시, SquadToDo가 모두 삭제되도록 변경

### ISSUE THREAD

**Issue by kimzoo2** [Eggmeoni-na/scrumble-BE#102]
## 세부내용

AS-IS : `ToDo`와 `SquadToDo를` 각각 삭제한다.
TO-BE : 
- ToDo 삭제 시, 관련된 SquadToDo를 삭제한다.
- SquadToDo 삭제 시, SquadToDo만 삭제한다.

### 구현 사항

- [ ] ToDo 삭제 로직 분리
- [ ] ToDo 삭제 로직 리팩토링
- [ ] SquadToDo 삭제 로직 리팩토링
